version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "pvc-angular-app"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started om 'date'
        - mvn test
  post_build:
    commands:
        - echo Build completed on 'date'
        - mvn package
artifacts:
    files:
        - target/spring-boot-ems-0.0.1-SNAPSHOT.war
