version: 0.2
phases:
  build:
    commands:
        - echo Build started om 'date'
        - mvn test
  post_build:
    commands:
        - echo Build completed on 'date'
        - mvn package
artifacts:
    files:
        - target/spring-boot-ems-0.0.1-SNAPSHOT.war
